{
  "formatVersion": "1.1",
  "component": {
    "group": "io.mydaourite",
    "module": "mydaourite-springrestclient",
    "version": "6.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "4.0.2.RELEASE"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework.ws",
          "module": "spring-ws-core",
          "version": {
            "requires": "2.4.0.RELEASE"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-remoting",
          "version": {
            "requires": "2.0.8"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "axis",
          "module": "axis-wsdl4j",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.1.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents.core5",
          "module": "httpcore5",
          "version": {
            "requires": "5.1.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "woodstox-core-asl",
          "version": {
            "requires": "4.4.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "io.mydaourite",
          "module": "MyDAOurite-SpringAdvice",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mydaourite-springrestclient-6.0.2.jar",
          "url": "mydaourite-springrestclient-6.0.2.jar",
          "size": 86654,
          "sha512": "ee7027bad66df298854a19bd72612f3f577c00dcf6fed7ee2969ac991a6019dc8725178af28c7ac42ec0718df104d5e22320b4608fdf8cb416ed55b9ff950c38",
          "sha256": "e85a9802afe3fcdb5e073eff7213c3b6556fa8397fb9d5f91fef981e77b17b73",
          "sha1": "a64478c5162c73f96a9f066d692ddd1fad4a4eb1",
          "md5": "7f6a891948683160b95677733f876f4c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "4.0.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "4.0.2.RELEASE"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework.ws",
          "module": "spring-ws-core",
          "version": {
            "requires": "2.4.0.RELEASE"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-remoting",
          "version": {
            "requires": "2.0.8"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "javax.xml",
          "module": "jaxrpc-api",
          "version": {
            "requires": "1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.axis",
          "module": "axis",
          "version": {
            "requires": "1.4"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "axis",
          "module": "axis-wsdl4j",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "commons-discovery",
          "module": "commons-discovery",
          "version": {
            "requires": "0.5"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.3"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents.client5",
          "module": "httpclient5",
          "version": {
            "requires": "5.1.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents.core5",
          "module": "httpcore5",
          "version": {
            "requires": "5.1.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-csv",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-xml",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.codehaus.woodstox",
          "module": "woodstox-core-asl",
          "version": {
            "requires": "4.4.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.dataformat",
          "module": "jackson-dataformat-yaml",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "io.mydaourite",
          "module": "MyDAOurite-SpringAdvice",
          "version": {
            "requires": "1.1.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.2.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-web",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "requires": "2.17.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        },
        {
          "group": "io.netty",
          "module": "netty-all",
          "version": {
            "requires": "4.1.14.Final"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "mydaourite-springrestclient-6.0.2.jar",
          "url": "mydaourite-springrestclient-6.0.2.jar",
          "size": 86654,
          "sha512": "ee7027bad66df298854a19bd72612f3f577c00dcf6fed7ee2969ac991a6019dc8725178af28c7ac42ec0718df104d5e22320b4608fdf8cb416ed55b9ff950c38",
          "sha256": "e85a9802afe3fcdb5e073eff7213c3b6556fa8397fb9d5f91fef981e77b17b73",
          "sha1": "a64478c5162c73f96a9f066d692ddd1fad4a4eb1",
          "md5": "7f6a891948683160b95677733f876f4c"
        }
      ]
    }
  ]
}
